[shorturls]
gh = "github:{path}"

[all_follow]

[inputs.tack]
url = "github:manic-systems/tack"

[inputs.nixpkgs]
url = "https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz"

[inputs.crane]
url = "github:ipetkov/crane"
